// Copyright 2026 Scott Friedman
// SPDX-License-Identifier: Apache-2.0

package bundle

import (
	"fmt"
	"strings"
)

// The cover note. DESIGN §6 is specific about what it must do: explain the
// blast-radius argument in CISO-legible terms — the role can only place accounts
// into the named OU, the delegation only touches policies on that OU, and SCPs
// central IT attaches *above* the OU still bind everything below, so the delegate
// can add restrictions and never loosen the institutional floor.
//
// The audience is someone who will spend ten minutes on this and then either
// approve it or put it in a queue. So the structure is: what is being asked for,
// what it cannot do, what to check, then how to apply it. The "cannot do" section
// is above the instructions on purpose — it is the part that decides the answer.

// README renders the bundle's cover note.
func README(r *Request) ([]byte, error) {
	if err := r.Validate(); err != nil {
		return nil, err
	}
	ou := r.ouScope()
	var b strings.Builder
	w := func(format string, args ...any) {
		if len(args) == 0 {
			b.WriteString(format)
			return
		}
		fmt.Fprintf(&b, format, args...)
	}

	w("# Account vending request: account %s\n", r.MemberAccountID)
	w("\n")
	w("Generated by automat %s at %s. Reply to %s.\n", r.ToolVersion, r.GeneratedAt, r.RequesterContact)
	w("\n")
	w("Account %s needs to create AWS member accounts with compliance controls attached\n", r.MemberAccountID)
	w("at creation, inside one organizational unit. It cannot do that today: creating an\n")
	w("account and creating an OU are management-account-only operations in AWS\n")
	w("Organizations and cannot be delegated. This bundle contains the two things that\n")
	w("would let it, both scoped to a single OU subtree.\n")
	w("\n")
	w("## What is being asked for\n")
	w("\n")
	w("| | |\n")
	w("|---|---|\n")
	w("| Requesting account | %s |\n", r.MemberAccountID)
	if r.MemberRoleARN != "" {
		w("| Trusted principal | `%s` (one role, not the whole account) |\n", r.MemberRoleARN)
	} else {
		w("| Trusted principal | `%s` (the whole account — see \"Narrowing it further\") |\n",
			r.trustPrincipal())
	}
	w("| Organization | %s, management account %s |\n", r.OrgID, r.ManagementAccountID)
	if r.ouIsPlaceholder() {
		w("| Target OU | does not exist yet — proposed name %q (see `ou.md`) |\n", r.TargetOUName)
	} else {
		w("| Target OU | %s |\n", ou)
	}
	w("| Role to create | `%s` in the management account |\n", r.VendorRoleName)
	w("\n")
	w("Two grants, because AWS splits the capability two ways:\n")
	w("\n")
	w("1. **`delegation-policy.json`** — a resource-based delegation policy on the\n")
	w("   organization. Lets account %s create, update, tag, attach, and detach service\n", r.MemberAccountID)
	w("   control policies **that it created**, on **that OU subtree only**.\n")
	w("2. **`vendor-role.cfn.yaml`** (or **`vendor-role.tf`** — deploy one, not both) — one\n")
	w("   IAM role in the management account. Lets account %s create member accounts and\n", r.MemberAccountID)
	w("   move them **into that OU subtree only**. It holds no policy permissions at all.\n")
	w("\n")
	w("## Blast radius: what this cannot do\n")
	w("\n")
	w("This is the section worth your ten minutes.\n")
	w("\n")
	w("- **It cannot place an account anywhere else.** `organizations:MoveAccount` is\n")
	w("  restricted by resource to OU %s and its descendants as the destination. An\n", ou)
	w("  attempt to move an account into any other OU, or to the root, is denied by IAM.\n")
	w("- **It cannot move an account it did not create.** The same statement is also\n")
	w("  conditioned on the account carrying `automat:vended-by`. This matters more than\n")
	w("  it looks: an account has exactly one parent OU, so moving an account *into* this\n")
	w("  OU would move it *out of* wherever it was — and out from under the service\n")
	w("  control policies attached there. Without that condition, \"may move accounts into\n")
	w("  the delegated OU\" would be a way to lift one of your accounts out of your\n")
	w("  baseline without touching the baseline itself.\n")
	w("- **It cannot touch your policies.** The delegation allows policy modification only\n")
	w("  on policies already tagged `automat:managed-by=automat`, which only this tool's\n")
	w("  own policies carry. An SCP you wrote and attached to that same OU cannot be\n")
	w("  updated, deleted, or detached by the delegate. This is the condition most easily\n")
	w("  missed in review, and it is the one that separates \"can add restrictions\" from\n")
	w("  \"can remove yours\".\n")
	w("- **It cannot tag its way around that.** The bullet above depends on the delegate\n")
	w("  being unable to *write* the tag those conditions read — a principal that can set\n")
	w("  the tag a condition checks is not constrained by that condition, and the two\n")
	w("  halves of that mistake can sit in different files. Both files are written so no\n")
	w("  tag either one reads is a tag either one can write:\n")
	w("  - In `delegation-policy.json`, `organizations:TagResource` applies only to\n")
	w("    resources that *already* carry `automat:managed-by=automat`. It cannot put that\n")
	w("    tag on an SCP of yours, because it would need the tag to be there already.\n")
	w("  - In the role, `organizations:TagResource` reaches no policy resource at all, and\n")
	w("    its tag keys are a closed list of three inventory labels.\n")
	w("    `automat:vended-by` and `automat:ou` are deliberately absent from that list:\n")
	w("    they are the keys the conditions above read, they are set once at account\n")
	w("    creation, and nothing can set them again. The grant is split in two so each\n")
	w("    half can be confined by whatever actually confines it — accounts by the\n")
	w("    `automat:vended-by` tag, OUs by the subtree in their ARN.\n")
	w("  If you check one thing across both files, check that: no tag key that appears in\n")
	w("  a `Condition` anywhere appears in a `TagResource` statement's allowed keys.\n")
	w("- **It cannot loosen anything you enforce.** Service control policies you attach\n")
	w("  above OU %s — at the root or at a parent OU — still apply to every account\n", ou)
	w("  below it. SCPs intersect: the effective permissions of a vended account are what\n")
	w("  *both* your policies and automat's allow. The delegate can only make an account\n")
	w("  more restricted than your baseline, never less. Your institutional floor holds.\n")
	w("- **It cannot create an untagged account.** `organizations:CreateAccount` is\n")
	w("  conditioned on `aws:RequestTag/automat:vended-by` and `aws:RequestTag/automat:ou`,\n")
	w("  so every account it creates is attributable to this request in your own\n")
	w("  CloudTrail. An attempt to create one without those tags fails.\n")
	w("- **It cannot be used by anyone else.** The role's trust policy names exactly one\n")
	w("  principal and requires an `sts:ExternalId`. Knowing the role ARN is not enough.\n")
	w("- **It cannot close, suspend, or remove an account** — none of those actions appear\n")
	w("  in either file. Nor can it enable or disable an AWS service, change billing, or\n")
	w("  read anything *inside* any account: no S3 object, no database, no log. What it\n")
	w("  can read about your accounts is the next bullet, and it is not nothing.\n")
	w("- **What it can read is organization-wide, and that is worth a paragraph rather\n")
	w("  than a footnote.** Every other grant in these files is confined to OU %s. The\n", ou)
	w("  read statement is not, because it cannot be: naming an OU means resolving its\n")
	w("  parents, so the delegate must be able to walk the tree above itself. Concretely,\n")
	w("  account %s will be able to list and describe:\n", r.MemberAccountID)
	w("  - **every account in the organization, including its root-user email address**\n")
	w("    and account name. `organizations:DescribeAccount` and `ListAccounts` return\n")
	w("    those, and their resource ARNs cover the whole organization — an Organizations\n")
	w("    account ARN does not encode which OU the account is in, so there is no way to\n")
	w("    narrow this by resource. If those addresses are individual staff mailboxes\n")
	w("    rather than a shared alias, that is a directory of them.\n")
	w("  - **the full text of every service control policy in the organization**, yours\n")
	w("    included, via `DescribePolicy` and `DescribeEffectivePolicy`. Reading a policy\n")
	w("    is not modifying it — the modification grants are tag-conditioned, which is the\n")
	w("    bullet above — but a policy is a map of what your controls do and do not cover.\n")
	w("  - the whole OU tree and which accounts and policies sit where.\n")
	w("  None of this is a write and none of it reaches into an account. It is disclosure,\n")
	w("  and whether it is acceptable is your call and not automat's: if the member\n")
	w("  account is run by a different group than yours, decide about it deliberately\n")
	w("  rather than discovering it later. There is no narrower version of this grant that\n")
	w("  leaves the tool able to report on what it did.\n")
	w("\n")
	w("What it *can* do, stated plainly: create AWS accounts (which cost money and count\n")
	w("against your organization's account quota), place them in one OU, attach further\n")
	w("restrictions to that OU, and read the organization's structure — including every\n")
	w("account's root-user email and every SCP's contents, as above.\n")
	w("\n")
	w("## What to check before approving\n")
	w("\n")
	w("Read both files. They are short on purpose — around a hundred lines each, five\n")
	w("statements in the policy and six in the role — and reading them in full is a\n")
	w("realistic ask, which is the point of scoping it this way.\n")
	w("\n")
	w("1. `delegation-policy.json`: confirm the `Principal` is the account you expect, and\n")
	w("   that every `Resource` names organization %s. Only the last statement —\n", r.OrgID)
	w("   `AutomatReadTheOrganization...` — should reach past OU %s. That one is\n", ou)
	w("   organization-wide on purpose and grants reads only; the blast-radius section\n")
	w("   above says exactly what those reads expose, which includes every account's\n")
	w("   root-user email and every SCP's text. Confirm you are content with that, and\n")
	w("   confirm no *other* statement's `Resource` list reaches past the OU.\n")
	w("2. **Both `TagResource` statements — one per file — and check them together.**\n")
	w("   This is where the difference is least obvious and the consequence is total,\n")
	w("   because the tags in these documents are what authorization rests on.\n")
	w("   - In `delegation-policy.json`: the condition is `aws:ResourceTag`, not\n")
	w("     `aws:RequestTag`. `RequestTag` would let the delegate put automat's tag on\n")
	w("     *your* SCP and inherit every permission the other statements grant over\n")
	w("     automat's own.\n")
	w("   - In the role: no `Resource` is `*` and none names a policy, and the\n")
	w("     `aws:TagKeys` list is `StringEquals` over named keys rather than `StringLike`\n")
	w("     over `automat:*`. A `*` resource reaches your SCPs; an `automat:*` key bound\n")
	w("     admits `automat:vended-by`, which is the tag the `MoveAccount` statement in\n")
	w("     the same file checks.\n")
	w("3. The role's `AssumeRolePolicyDocument`: confirm the principal, and that the\n")
	w("   `sts:ExternalId` condition is present.\n")
	w("4. The role's inline policy: confirm no `organizations:*Policy` action appears in\n")
	w("   it at all. Policy permissions belong to the other file.\n")
	w("5. `MoveAccount`: the OU resources are this subtree rather than `*`, **and** the\n")
	w("   statement carries the `automat:vended-by` condition. The `account/...` resource\n")
	w("   in it is org-wide no matter what — an Organizations account ARN does not encode\n")
	w("   which OU the account is in — so that condition is what confines it.\n")
	w("6. `CreateOrganizationalUnit`: the resources are the OU subtree, not `*`.\n")
	w("\n")
	w("## Applying it\n")
	w("\n")
	if r.ouIsPlaceholder() {
		w("0. **Create the OU first** and replace the placeholder in every file. See\n")
		w("   `ou.md` — it lists exactly which files and lines change.\n")
	}
	w("1. Attach the delegation policy to the organization, from the management account.\n")
	w("   **Check for an existing policy first — this is a destructive step if you skip\n")
	w("   it.** An organization has exactly one resource policy and\n")
	w("   `put-resource-policy` replaces it wholesale; there is no merge mode and no\n")
	w("   confirmation prompt. If something else already delegates through it, running the\n")
	w("   second command below without reading the first's output silently revokes that.\n")
	w("\n")
	w("   ```\n")
	w("   # 1a. What is there now? \"ResourcePolicyNotFoundException\" means nothing is,\n")
	w("   #     and you can go straight to 1b.\n")
	w("   aws organizations describe-resource-policy\n")
	w("\n")
	w("   # 1b. Only if 1a found no existing policy:\n")
	w("   aws organizations put-resource-policy \\\n")
	w("     --content file://delegation-policy.json\n")
	w("   ```\n")
	w("\n")
	w("   If 1a *did* return a policy, do not run 1b. Merge these statements into the\n")
	w("   existing document by hand and put the combined result instead — the `Sid`s in\n")
	w("   `delegation-policy.json` are all prefixed `Automat` so they cannot collide with\n")
	w("   yours.\n")
	w("2. Create the role, from the management account:\n")
	w("\n")
	w("   ```\n")
	w("   aws cloudformation deploy \\\n")
	w("     --template-file vendor-role.cfn.yaml \\\n")
	w("     --stack-name automat-vendor-role \\\n")
	w("     --capabilities CAPABILITY_NAMED_IAM\n")
	w("   ```\n")
	w("\n")
	w("   Or `terraform apply` with `vendor-role.tf`. The two are equivalent; deploy one.\n")
	w("3. Reply to %s with the role ARN, which is\n", r.RequesterContact)
	w("   `%s` unless you renamed it", r.vendorRoleARN())
	if r.ouIsPlaceholder() {
		w(", and the OU id you created")
	}
	w(".\n")
	w("\n")
	w("The requester then runs `automat preflight`, which re-checks all of this from their\n")
	w("side and reports what is still missing. Nothing in this bundle needs to be right\n")
	w("first try.\n")
	w("\n")
	w("## Narrowing it further\n")
	w("\n")
	if r.MemberRoleARN == "" {
		w("This bundle names account %s as the trusted principal, which trusts every\n", r.MemberAccountID)
		w("identity in it — including ones created later by someone else in that account. If\n")
		w("you would rather trust one role, ask the requester for the ARN of the role that\n")
		w("runs automat and substitute it for `%s` in the trust\n", r.trustPrincipal())
		w("policy and in `delegation-policy.json`. automat supports this and recommends it;\n")
		w("the requester can regenerate the bundle that way.\n")
	} else {
		w("This bundle already names one role rather than the whole account, which is the\n")
		w("narrower of the two forms automat supports.\n")
	}
	w("\n")
	w("## About this file\n")
	w("\n")
	w("**This bundle contains a live `sts:ExternalId`** (in the trust policy in both role\n")
	w("templates). It is not a password — it defends the role against being assumed by a\n")
	w("third party that learns its ARN, and it does nothing if an attacker already has\n")
	w("credentials in account %s. But it is only useful while it is not widely known:\n", r.MemberAccountID)
	w("send this bundle the way you would send any internal configuration, and do not\n")
	w("commit it to a public repository. Both sides must configure the same value, which\n")
	w("is why it is written here rather than left as a placeholder for each side to invent\n")
	w("separately.\n")
	w("\n")
	w("Every other value here is an account id, an OU id, or an ARN — none is secret.\n")
	w("\n")
	w("This bundle was generated mechanically from the requester's configuration. Every\n")
	w("value in it is an identifier — an account id, an OU id, an ARN, a role name, an\n")
	w("OU name — checked against a pattern and quoted where it is rendered. None of it\n")
	w("is a paragraph the requester wrote, and nothing in it should be read as an\n")
	w("argument for approving it. One value is a short human-chosen label, the proposed\n")
	w("OU name, so treat that one as text the requester picked rather than as a fact.\n")
	w("If you want the reasoning, ask %s.\n", r.RequesterContact)

	return []byte(b.String()), nil
}

// OUInstructions renders ou.md.
//
// This file exists because the most common answer to an onboarding request is
// "sure, but the OU does not exist yet" — and the operator who then creates it
// must jump back into three generated files to replace a placeholder. Listing
// exactly where keeps a half-substituted bundle from being deployed, which would
// produce a role scoped to an OU that does not exist and a jam nobody would
// diagnose from the error.
func OUInstructions(r *Request) ([]byte, error) {
	if err := r.Validate(); err != nil {
		return nil, err
	}
	var b strings.Builder
	w := func(format string, args ...any) {
		if len(args) == 0 {
			b.WriteString(format)
			return
		}
		fmt.Fprintf(&b, format, args...)
	}

	w("# The target organizational unit\n")
	w("\n")
	if !r.ouIsPlaceholder() {
		w("**Nothing to do here.** This bundle names an existing OU, %s, and every\n", r.TargetOU)
		w("file in it is ready to apply as written. This file is included so the bundle has\n")
		w("the same five files every time; jump to `README.md`.\n")
		w("\n")
		w("For reference, the delegation is scoped to:\n")
		w("\n")
		w("```\n")
		w("organization %s\n", r.OrgID)
		w("  management account %s\n", r.ManagementAccountID)
		w("    OU %s        <- the delegated subtree\n", r.TargetOU)
		w("      (vended accounts land here)\n")
		w("```\n")
		return []byte(b.String()), nil
	}

	w("This bundle needs an OU that does not exist yet. **Create it first**, then replace\n")
	w("the placeholder in the other files. Three steps.\n")
	w("\n")
	w("## 1. Create the OU\n")
	w("\n")
	w("From the management account (%s). The proposed name is %q; use whatever\n",
		r.ManagementAccountID, r.TargetOUName)
	w("your naming convention requires — automat does not care about the name, only the id.\n")
	w("\n")
	w("```\n")
	w("aws organizations list-roots --query 'Roots[0].Id' --output text\n")
	w("aws organizations create-organizational-unit \\\n")
	w("  --parent-id <the root id, or a parent OU id> \\\n")
	w("  --name %q\n", r.TargetOUName)
	w("```\n")
	w("\n")
	w("The OU may sit anywhere in your hierarchy. Under a parent OU is often the right\n")
	w("place: service control policies you attach to that parent still bind everything\n")
	w("inside this one, so nesting it is how you keep it under an existing baseline\n")
	w("rather than beside it.\n")
	w("\n")
	w("Note the returned `Id` — the `%s` form. That is the only value needed below.\n", "ou-xxxx-xxxxxxxx")
	w("\n")
	w("## 2. Replace the placeholder\n")
	w("\n")
	w("Every generated file contains the literal string:\n")
	w("\n")
	w("```\n")
	w("%s\n", r.ouScope())
	w("```\n")
	w("\n")
	w("Replace all occurrences with the real OU id, in these files:\n")
	w("\n")
	w("| File | Occurrences are in |\n")
	w("|---|---|\n")
	w("| `delegation-policy.json` | the `Resource` arrays |\n")
	w("| `vendor-role.cfn.yaml` | the `MoveAccount` and `CreateOrganizationalUnit` resources, the tag value, and the description |\n")
	w("| `vendor-role.tf` | `local.automat_target_ou` (one place; everything else references it) |\n")
	w("| `README.md` | prose only — no need to edit, but it will read oddly until you do |\n")
	w("\n")
	w("A quick check from the bundle directory:\n")
	w("\n")
	w("```\n")
	w("grep -rn %s .\n", r.ouScope())
	w("```\n")
	w("\n")
	w("**A missed occurrence fails loudly rather than quietly.** The placeholder is not a\n")
	w("valid OU id, so AWS rejects a policy or template that still contains one. You\n")
	w("cannot end up with a role scoped to nothing.\n")
	w("\n")
	w("## 3. Apply the bundle\n")
	w("\n")
	w("Then follow `README.md`, and reply with both the role ARN and the OU id — the\n")
	w("requester needs the id for their own configuration.\n")
	w("\n")
	w("## What the delegation ends up scoped to\n")
	w("\n")
	w("```\n")
	w("organization %s\n", r.OrgID)
	w("  management account %s\n", r.ManagementAccountID)
	w("    ...\n")
	w("      OU %q, id <the id from step 1>   <- the delegated subtree\n", r.TargetOUName)
	w("        (vended accounts land here)\n")
	w("```\n")
	w("\n")
	w("Account %s can act inside that subtree and nowhere else. Any service control\n", r.MemberAccountID)
	w("policy you attach at or above the parent still applies to everything in it.\n")

	return []byte(b.String()), nil
}
