// Copyright 2026 Scott Friedman
// SPDX-License-Identifier: Apache-2.0

package bundle

import (
	"fmt"
	"strings"
)

// The vendor role: the "vending half" of DESIGN §5.
//
// organizations:CreateAccount and CreateOrganizationalUnit cannot be delegated
// (DESIGN §3, facts 1 and 2), so the member account borrows them through a role in
// the management account instead. DESIGN §5 is explicit that this role carries no
// policy actions — those flow through the delegation policy — which is what keeps
// it reviewable in the length central IT will actually read.
//
// # Why these templates are written by hand rather than by a YAML/HCL library
//
// Both files are *executed* by a privileged operator. A generated YAML or HCL
// document with quoting decided by a marshaler is a document nobody reviews line
// by line, and this is a file whose whole purpose is to be reviewed line by line.
// So the templates are literal text with a fixed shape, and the safety comes from
// the input side: Request.Validate admits no character that can terminate a
// string, open a substitution, or start a line in either format, which is checked
// directly by TestNoPatternAdmitsAStructuralCharacter and
// TestNoTemplateSeesAnUnvalidatedValue.

// vendorRoleActions are the Organizations actions the role grants, with the
// reason each is present. A reviewer's first question is "why this one", and an
// answer per action is the difference between an approved bundle and a meeting.
var vendorRoleActions = []struct {
	action string
	why    string
}{
	{"organizations:CreateAccount", "cannot be delegated to a member account (the reason this role exists)"},
	{"organizations:DescribeCreateAccountStatus", "account creation is asynchronous; this polls it"},
	{"organizations:MoveAccount", "a new account lands under the root and must be moved into the OU"},
	{"organizations:CreateOrganizationalUnit", "cannot be delegated either; creates sub-OUs inside the subtree"},
	{"organizations:TagResource", "applies the automat:* tags that identify a vended account"},
	{"organizations:DescribeAccount", "read-back after create and move"},
	{"organizations:DescribeOrganizationalUnit", "resolves the destination OU"},
	{"organizations:ListParents", "confirms an account landed where it was moved"},
	{"organizations:ListAccountsForParent", "inventory for `automat list`"},
	{"organizations:ListOrganizationalUnitsForParent", "navigates the subtree"},
	{"organizations:ListRoots", "the root id is needed to address the subtree"},
}

// mutableTagKeys is every tag key the vendor role may write after an account
// exists, and it is a closed list because of what is NOT on it.
//
// DESIGN §217 defines five tags on a vended account. Two of them --
// automat:vended-by and automat:ou -- are read by conditions in this bundle:
// MoveAccount requires an account to carry vended-by, and the delegation policy's
// owner tag works the same way. A tag a condition reads must not be writable by
// the principal the condition constrains, or the condition constrains nothing. Both
// are set exactly once, at CreateAccount, through aws:RequestTag, where the value
// is fixed by the template rather than chosen at call time.
//
// The three below are cost-allocation and inventory labels. They change when an
// account is re-vended against a newer artifact, so they must stay writable -- and
// they are safe to leave writable precisely because no condition anywhere reads
// them. TestNoConditionReadsATagTheBundleLetsTheDelegateWrite enforces that
// property over both documents, so adding a condition on one of these keys without
// removing it here fails the build.
var mutableTagKeys = []string{
	"automat:artifact-id",
	"automat:artifact-sha256",
	"automat:version",
}

// VendorRoleCFN renders vendor-role.cfn.yaml.
func VendorRoleCFN(r *Request) ([]byte, error) {
	if err := r.Validate(); err != nil {
		return nil, err
	}
	ou := r.ouScope()
	var b strings.Builder

	w := func(format string, args ...any) {
		if len(args) == 0 {
			b.WriteString(format)
			return
		}
		fmt.Fprintf(&b, format, args...)
	}

	w("AWSTemplateFormatVersion: '2010-09-09'\n")
	w("Description: >-\n")
	w("  The automat vendor role. Creates one IAM role in the organization's management\n")
	w("  account that account %s may assume to create and place member accounts inside\n", r.MemberAccountID)
	w("  organizational unit %s, and nothing else. Deploy in the management account.\n", ou)
	w("\n")
	w("# Generated by automat %s at %s. Review before deploying: this file is the\n", r.ToolVersion, r.GeneratedAt)
	w("# entire grant being requested, and it is meant to be read in full.\n")
	if r.ouIsPlaceholder() {
		w("#\n")
		w("# BEFORE DEPLOYING: create the organizational unit, then replace every\n")
		w("# occurrence of %s below with the real OU id. AWS rejects the\n", ou)
		w("# template while the placeholder remains, so this cannot be forgotten silently.\n")
	}
	w("\n")
	w("Resources:\n")
	w("  AutomatVendorRole:\n")
	w("    Type: AWS::IAM::Role\n")
	w("    Properties:\n")
	// Quoted, because YAML 1.1 resolves plain scalars by content: an unquoted
	// role name of "off", "no", "true", "null", or "0755" arrives at
	// CloudFormation as a boolean, null, or integer rather than the string the
	// operator typed. Every one of those is a legal IAM role name, so validation
	// cannot reject them without rejecting reasonable input, and a denylist of one
	// parser's type-resolution rules is not a defense. reRoleName admits no single
	// quote, so quoting here cannot itself be escaped.
	w("      RoleName: '%s'\n", r.VendorRoleName)
	w("      Description: >-\n")
	w("        Lets account %s vend member accounts into OU %s. Managed by automat.\n", r.MemberAccountID, ou)
	w("      MaxSessionDuration: 3600\n")
	w("      AssumeRolePolicyDocument:\n")
	w("        Version: '2012-10-17'\n")
	w("        Statement:\n")
	w("          - Sid: AutomatMemberAccountMayAssumeWithExternalId\n")
	w("            Effect: Allow\n")
	w("            Principal:\n")
	w("              AWS: '%s'\n", r.trustPrincipal())
	w("            Action: sts:AssumeRole\n")
	w("            Condition:\n")
	w("              StringEquals:\n")
	// The confused-deputy defense. Without it, any account that learns the role
	// ARN could assume it; with it, only a caller told the ExternalId can.
	w("                sts:ExternalId: '%s'\n", r.ExternalID)
	w("      Policies:\n")
	w("        - PolicyName: automat-vend\n")
	w("          PolicyDocument:\n")
	w("            Version: '2012-10-17'\n")
	w("            Statement:\n")

	w("              # Account creation. The tag condition means every account this role\n")
	w("              # creates is attributable: an untagged account cannot be created at all.\n")
	w("              - Sid: CreateTaggedAccounts\n")
	w("                Effect: Allow\n")
	w("                Action:\n")
	w("                  - organizations:CreateAccount\n")
	w("                Resource: '*'\n")
	w("                Condition:\n")
	w("                  StringEquals:\n")
	w("                    aws:RequestTag/automat:vended-by: '%s'\n", r.MemberAccountID)
	w("                    aws:RequestTag/automat:ou: '%s'\n", ou)
	w("\n")
	w("              # Placement. This is the statement that bounds the blast radius, and it\n")
	w("              # is bounded at both ends because MoveAccount authorizes against the\n")
	w("              # destination parent AND the account being moved.\n")
	w("              #\n")
	w("              # Destination: this OU or one below it, by resource. Account: only one\n")
	w("              # this role vended, by condition. The account resource pattern cannot\n")
	w("              # express the second -- an Organizations account ARN encodes the\n")
	w("              # organization, not the account's OU, so account/<org>/* is every\n")
	w("              # account here. Without the condition this statement would read \"move\n")
	w("              # ANY account in the organization into this OU\", and since an account\n")
	w("              # has exactly one parent, moving one IN moves it OUT from under\n")
	w("              # whatever service control policies bound it before.\n")
	w("              - Sid: MoveAccountsIntoTheDelegatedSubtreeOnly\n")
	w("                Effect: Allow\n")
	w("                Action:\n")
	w("                  - organizations:MoveAccount\n")
	w("                Resource:\n")
	w("                  - !Sub 'arn:${AWS::Partition}:organizations::${AWS::AccountId}:account/%s/*'\n", r.OrgID)
	w("                  - !Sub 'arn:${AWS::Partition}:organizations::${AWS::AccountId}:ou/%s/%s'\n", r.OrgID, ou)
	w("                  - !Sub 'arn:${AWS::Partition}:organizations::${AWS::AccountId}:ou/%s/%s/*'\n", r.OrgID, ou)
	w("                Condition:\n")
	w("                  StringEquals:\n")
	w("                    aws:ResourceTag/automat:vended-by: '%s'\n", r.MemberAccountID)
	w("\n")
	w("              # Sub-OUs, restricted to the delegated subtree as the parent.\n")
	w("              - Sid: CreateOrganizationalUnitsInsideTheSubtreeOnly\n")
	w("                Effect: Allow\n")
	w("                Action:\n")
	w("                  - organizations:CreateOrganizationalUnit\n")
	w("                Resource:\n")
	w("                  - !Sub 'arn:${AWS::Partition}:organizations::${AWS::AccountId}:ou/%s/%s'\n", r.OrgID, ou)
	w("                  - !Sub 'arn:${AWS::Partition}:organizations::${AWS::AccountId}:ou/%s/%s/*'\n", r.OrgID, ou)
	w("\n")
	w("              # Tagging. Two bounds, and both are load-bearing.\n")
	w("              #\n")
	w("              # The RESOURCE bound excludes policies. On '*' this statement would\n")
	w("              # reach every service control policy ARN in the organization, and\n")
	w("              # tagging one of yours with automat:managed-by=automat would hand the\n")
	w("              # delegation policy in delegation-policy.json permission to rewrite\n")
	w("              # it -- that document gates update, delete, and detach on exactly\n")
	w("              # that tag. The role would never touch policy CONTENT; it would just\n")
	w("              # forge the label that decides who may.\n")
	w("              #\n")
	w("              # The KEY bound is an explicit list, not automat:*. The keys omitted\n")
	w("              # from it are omitted on purpose: automat:vended-by and automat:ou\n")
	w("              # are read by conditions elsewhere in this bundle, so a principal\n")
	w("              # that could write them would not be constrained by those conditions.\n")
	w("              # Both are applied once, at CreateAccount, through aws:RequestTag\n")
	w("              # above -- so nothing legitimate needs to set them again, and this\n")
	w("              # statement cannot. The three keys below are cost-allocation and\n")
	w("              # inventory labels that no condition anywhere reads, which is what\n")
	w("              # makes them safe to leave mutable.\n")
	w("              # Accounts and OUs are separate statements because only one of them\n")
	w("              # can be confined by a tag. account/<org>/* is every account in the\n")
	w("              # organization -- an Organizations account ARN encodes the org, not\n")
	w("              # the OU -- so the account statement carries a condition instead: the\n")
	w("              # account must already be one this role vended. A fresh OU has no\n")
	w("              # tags at all, so the same condition there would make tagging a\n")
	w("              # newly created OU impossible; its ARN does encode the subtree, so\n")
	w("              # the resource bound is a real one.\n")
	w("              - Sid: TagAccountsThisRoleVended\n")
	w("                Effect: Allow\n")
	w("                Action:\n")
	w("                  - organizations:TagResource\n")
	w("                Resource:\n")
	w("                  - !Sub 'arn:${AWS::Partition}:organizations::${AWS::AccountId}:account/%s/*'\n", r.OrgID)
	w("                Condition:\n")
	w("                  StringEquals:\n")
	w("                    aws:ResourceTag/automat:vended-by: '%s'\n", r.MemberAccountID)
	w("                  ForAllValues:StringEquals:\n")
	w("                    aws:TagKeys:\n")
	for _, k := range mutableTagKeys {
		w("                      - '%s'\n", k)
	}
	w("\n")
	w("              - Sid: TagOrganizationalUnitsInTheSubtree\n")
	w("                Effect: Allow\n")
	w("                Action:\n")
	w("                  - organizations:TagResource\n")
	w("                Resource:\n")
	w("                  - !Sub 'arn:${AWS::Partition}:organizations::${AWS::AccountId}:ou/%s/%s'\n", r.OrgID, ou)
	w("                  - !Sub 'arn:${AWS::Partition}:organizations::${AWS::AccountId}:ou/%s/%s/*'\n", r.OrgID, ou)
	w("                Condition:\n")
	w("                  ForAllValues:StringEquals:\n")
	w("                    aws:TagKeys:\n")
	for _, k := range mutableTagKeys {
		w("                      - '%s'\n", k)
	}
	w("\n")
	w("              # The reads that make the above verifiable. No policy actions appear\n")
	w("              # anywhere in this role -- those flow through the delegation policy in\n")
	w("              # delegation-policy.json, which is separately scoped and separately\n")
	w("              # reviewable.\n")
	w("              - Sid: ReadTheOrganization\n")
	w("                Effect: Allow\n")
	w("                Action:\n")
	for _, a := range vendorRoleActions {
		switch a.action {
		case "organizations:CreateAccount", "organizations:MoveAccount",
			"organizations:CreateOrganizationalUnit", "organizations:TagResource":
			continue // granted above, each with its own condition
		}
		w("                  - %s\n", a.action)
	}
	w("                Resource: '*'\n")
	w("      Tags:\n")
	w("        - Key: automat:managed-by\n")
	w("          Value: automat\n")
	w("        - Key: automat:vended-by\n")
	w("          Value: '%s'\n", r.MemberAccountID)
	w("        - Key: automat:ou\n")
	w("          Value: '%s'\n", ou)
	w("\n")
	w("Outputs:\n")
	w("  VendorRoleArn:\n")
	w("    Description: Set this as vendor_role_arn in the requesting account's automat config.\n")
	w("    Value: !GetAtt AutomatVendorRole.Arn\n")

	return []byte(b.String()), nil
}

// VendorRoleTF renders vendor-role.tf, the same role for a management account run
// by Terraform.
//
// It is the same grant, not an approximation of it: TestCFNAndTFGrantTheSameThing
// compares the action sets and the conditions, because two files that drift apart
// mean central IT approved one thing and deployed another.
func VendorRoleTF(r *Request) ([]byte, error) {
	if err := r.Validate(); err != nil {
		return nil, err
	}
	ou := r.ouScope()
	var b strings.Builder
	w := func(format string, args ...any) {
		if len(args) == 0 {
			b.WriteString(format)
			return
		}
		fmt.Fprintf(&b, format, args...)
	}

	w("# The automat vendor role, for a management account managed by Terraform.\n")
	w("#\n")
	w("# Equivalent to vendor-role.cfn.yaml in the same bundle -- deploy one, not both.\n")
	w("# Generated by automat %s at %s. Review before applying: this file is the\n", r.ToolVersion, r.GeneratedAt)
	w("# entire grant being requested, and it is meant to be read in full.\n")
	if r.ouIsPlaceholder() {
		w("#\n")
		w("# BEFORE APPLYING: create the organizational unit, then replace every\n")
		w("# occurrence of %s below with the real OU id.\n", ou)
	}
	w("\n")
	w("data \"aws_partition\" \"current\" {}\n")
	w("data \"aws_caller_identity\" \"management\" {}\n")
	w("\n")
	w("locals {\n")
	w("  automat_org_id      = \"%s\"\n", r.OrgID)
	w("  automat_target_ou   = \"%s\"\n", ou)
	w("  automat_member_acct = \"%s\"\n", r.MemberAccountID)
	w("  automat_org_arn_base = format(\n")
	// Terraform's own format verbs, not Go's. Written straight to the builder so
	// there is no chance of a printf pass reading them.
	b.WriteString("    \"arn:%s:organizations::%s\",\n")
	w("    data.aws_partition.current.partition,\n")
	w("    data.aws_caller_identity.management.account_id,\n")
	w("  )\n")
	w("}\n")
	w("\n")
	w("resource \"aws_iam_role\" \"automat_vendor\" {\n")
	w("  name                 = \"%s\"\n", r.VendorRoleName)
	w("  description          = \"Lets account %s vend member accounts into OU %s. Managed by automat.\"\n",
		r.MemberAccountID, ou)
	w("  max_session_duration = 3600\n")
	w("\n")
	w("  assume_role_policy = jsonencode({\n")
	w("    Version = \"2012-10-17\"\n")
	w("    Statement = [{\n")
	w("      Sid       = \"AutomatMemberAccountMayAssumeWithExternalId\"\n")
	w("      Effect    = \"Allow\"\n")
	w("      Principal = { AWS = \"%s\" }\n", r.trustPrincipal())
	w("      Action    = \"sts:AssumeRole\"\n")
	w("      # The confused-deputy defense: without this condition any account that\n")
	w("      # learns the role ARN could assume it.\n")
	w("      Condition = {\n")
	w("        StringEquals = { \"sts:ExternalId\" = \"%s\" }\n", r.ExternalID)
	w("      }\n")
	w("    }]\n")
	w("  })\n")
	w("\n")
	w("  tags = {\n")
	w("    \"automat:managed-by\" = \"automat\"\n")
	w("    \"automat:vended-by\"  = \"%s\"\n", r.MemberAccountID)
	w("    \"automat:ou\"         = \"%s\"\n", ou)
	w("  }\n")
	w("}\n")
	w("\n")
	w("resource \"aws_iam_role_policy\" \"automat_vend\" {\n")
	w("  name = \"automat-vend\"\n")
	w("  role = aws_iam_role.automat_vendor.id\n")
	w("\n")
	w("  policy = jsonencode({\n")
	w("    Version = \"2012-10-17\"\n")
	w("    Statement = [\n")
	w("      {\n")
	w("        # Every account this role creates is attributable: an untagged account\n")
	w("        # cannot be created at all.\n")
	w("        Sid      = \"CreateTaggedAccounts\"\n")
	w("        Effect   = \"Allow\"\n")
	w("        Action   = [\"organizations:CreateAccount\"]\n")
	w("        Resource = \"*\"\n")
	w("        Condition = {\n")
	w("          StringEquals = {\n")
	w("            \"aws:RequestTag/automat:vended-by\" = local.automat_member_acct\n")
	w("            \"aws:RequestTag/automat:ou\"        = local.automat_target_ou\n")
	w("          }\n")
	w("        }\n")
	w("      },\n")
	w("      {\n")
	w("        # The statement that bounds the blast radius, bounded at both ends:\n")
	w("        # MoveAccount authorizes against the destination parent AND the account\n")
	w("        # being moved. Destination by resource, account by condition -- an\n")
	w("        # Organizations account ARN encodes the organization, not the account's\n")
	w("        # OU, so the account pattern below is every account here. Without the\n")
	w("        # condition this would read \"move ANY account into this OU\", and since\n")
	w("        # an account has one parent, moving it IN moves it OUT from under\n")
	w("        # whatever service control policies bound it before.\n")
	w("        Sid    = \"MoveAccountsIntoTheDelegatedSubtreeOnly\"\n")
	w("        Effect = \"Allow\"\n")
	w("        Action = [\"organizations:MoveAccount\"]\n")
	w("        Resource = [\n")
	w("          \"${local.automat_org_arn_base}:account/${local.automat_org_id}/*\",\n")
	w("          \"${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}\",\n")
	w("          \"${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}/*\",\n")
	w("        ]\n")
	w("        Condition = {\n")
	w("          StringEquals = {\n")
	w("            \"aws:ResourceTag/automat:vended-by\" = local.automat_member_acct\n")
	w("          }\n")
	w("        }\n")
	w("      },\n")
	w("      {\n")
	w("        Sid      = \"CreateOrganizationalUnitsInsideTheSubtreeOnly\"\n")
	w("        Effect   = \"Allow\"\n")
	w("        Action   = [\"organizations:CreateOrganizationalUnit\"]\n")
	w("        Resource = [\n")
	w("          \"${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}\",\n")
	w("          \"${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}/*\",\n")
	w("        ]\n")
	w("      },\n")
	w("      {\n")
	w("        # Two bounds, both load-bearing.\n")
	w("        #\n")
	w("        # The RESOURCE bound excludes policies: on \"*\" this statement would\n")
	w("        # reach every service control policy in the organization, and tagging\n")
	w("        # one of yours with automat:managed-by=automat would hand the delegation\n")
	w("        # policy permission to rewrite it -- that document gates update, delete,\n")
	w("        # and detach on exactly that tag.\n")
	w("        #\n")
	w("        # The KEY bound is an explicit list rather than automat:*, because\n")
	w("        # automat:vended-by and automat:ou are read by conditions elsewhere in\n")
	w("        # this bundle. Both are applied once at CreateAccount via aws:RequestTag,\n")
	w("        # so nothing legitimate re-sets them; the keys below are inventory labels\n")
	w("        # that no condition reads.\n")
	w("        # Accounts and OUs are split because only one can be confined by a tag:\n")
	w("        # account/<org>/* is every account in the organization, so that statement\n")
	w("        # carries a vended-by condition, while a fresh OU has no tags at all and\n")
	w("        # its ARN does encode the subtree.\n")
	w("        Sid      = \"TagAccountsThisRoleVended\"\n")
	w("        Effect   = \"Allow\"\n")
	w("        Action   = [\"organizations:TagResource\"]\n")
	w("        Resource = [\"${local.automat_org_arn_base}:account/${local.automat_org_id}/*\"]\n")
	w("        Condition = {\n")
	w("          StringEquals = {\n")
	w("            \"aws:ResourceTag/automat:vended-by\" = local.automat_member_acct\n")
	w("          }\n")
	w("          \"ForAllValues:StringEquals\" = {\n")
	w("            \"aws:TagKeys\" = [")
	for i, k := range mutableTagKeys {
		if i > 0 {
			w(", ")
		}
		w("\"%s\"", k)
	}
	w("]\n")
	w("          }\n")
	w("        }\n")
	w("      },\n")
	w("      {\n")
	w("        Sid      = \"TagOrganizationalUnitsInTheSubtree\"\n")
	w("        Effect   = \"Allow\"\n")
	w("        Action   = [\"organizations:TagResource\"]\n")
	w("        Resource = [\n")
	w("          \"${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}\",\n")
	w("          \"${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}/*\",\n")
	w("        ]\n")
	w("        Condition = {\n")
	w("          \"ForAllValues:StringEquals\" = {\n")
	w("            \"aws:TagKeys\" = [")
	for i, k := range mutableTagKeys {
		if i > 0 {
			w(", ")
		}
		w("\"%s\"", k)
	}
	w("]\n")
	w("          }\n")
	w("        }\n")
	w("      },\n")
	w("      {\n")
	w("        # No policy actions appear anywhere in this role -- those flow through\n")
	w("        # the delegation policy in delegation-policy.json, which is separately\n")
	w("        # scoped and separately reviewable.\n")
	w("        Sid      = \"ReadTheOrganization\"\n")
	w("        Effect   = \"Allow\"\n")
	w("        Resource = \"*\"\n")
	w("        Action = [\n")
	for _, a := range vendorRoleActions {
		switch a.action {
		case "organizations:CreateAccount", "organizations:MoveAccount",
			"organizations:CreateOrganizationalUnit", "organizations:TagResource":
			continue
		}
		w("          \"%s\",\n", a.action)
	}
	w("        ]\n")
	w("      },\n")
	w("    ]\n")
	w("  })\n")
	w("}\n")
	w("\n")
	w("output \"automat_vendor_role_arn\" {\n")
	w("  description = \"Set this as vendor_role_arn in the requesting account's automat config.\"\n")
	w("  value       = aws_iam_role.automat_vendor.arn\n")
	w("}\n")

	return []byte(b.String()), nil
}
