// Copyright 2026 Scott Friedman
// SPDX-License-Identifier: Apache-2.0

package bundle

import (
	"fmt"
	"strings"
)

// The vendor role: the "vending half" of DESIGN §5.
//
// organizations:CreateAccount and CreateOrganizationalUnit cannot be delegated
// (DESIGN §3, facts 1 and 2), so the member account borrows them through a role in
// the management account instead. DESIGN §5 is explicit that this role carries no
// policy actions — those flow through the delegation policy — which is what keeps
// it reviewable in the length central IT will actually read.
//
// # Why these templates are written by hand rather than by a YAML/HCL library
//
// Both files are *executed* by a privileged operator. A generated YAML or HCL
// document with quoting decided by a marshaler is a document nobody reviews line
// by line, and this is a file whose whole purpose is to be reviewed line by line.
// So the templates are literal text with a fixed shape, and the safety comes from
// the input side: Request.Validate admits no character that can terminate a
// string, open a substitution, or start a line in either format, which is checked
// directly by TestNoPatternAdmitsAStructuralCharacter and
// TestNoTemplateSeesAnUnvalidatedValue.

// vendorRoleActions are the Organizations actions the role grants, with the
// reason each is present. A reviewer's first question is "why this one", and an
// answer per action is the difference between an approved bundle and a meeting.
var vendorRoleActions = []struct {
	action string
	why    string
}{
	{"organizations:CreateAccount", "cannot be delegated to a member account (the reason this role exists)"},
	{"organizations:DescribeCreateAccountStatus", "account creation is asynchronous; this polls it"},
	{"organizations:MoveAccount", "a new account lands under the root and must be moved into the OU"},
	{"organizations:CreateOrganizationalUnit", "cannot be delegated either; creates sub-OUs inside the subtree"},
	{"organizations:TagResource", "applies the automat:* tags that identify a vended account"},
	{"organizations:DescribeAccount", "read-back after create and move"},
	{"organizations:DescribeOrganizationalUnit", "resolves the destination OU"},
	{"organizations:ListParents", "confirms an account landed where it was moved"},
	{"organizations:ListAccountsForParent", "inventory for `automat list`"},
	{"organizations:ListOrganizationalUnitsForParent", "navigates the subtree"},
	{"organizations:ListRoots", "the root id is needed to address the subtree"},
}

// VendorRoleCFN renders vendor-role.cfn.yaml.
func VendorRoleCFN(r *Request) ([]byte, error) {
	if err := r.Validate(); err != nil {
		return nil, err
	}
	ou := r.ouScope()
	var b strings.Builder

	w := func(format string, args ...any) {
		if len(args) == 0 {
			b.WriteString(format)
			return
		}
		fmt.Fprintf(&b, format, args...)
	}

	w("AWSTemplateFormatVersion: '2010-09-09'\n")
	w("Description: >-\n")
	w("  The automat vendor role. Creates one IAM role in the organization's management\n")
	w("  account that account %s may assume to create and place member accounts inside\n", r.MemberAccountID)
	w("  organizational unit %s, and nothing else. Deploy in the management account.\n", ou)
	w("\n")
	w("# Generated by automat %s at %s. Review before deploying: this file is the\n", r.ToolVersion, r.GeneratedAt)
	w("# entire grant being requested, and it is meant to be read in full.\n")
	if r.ouIsPlaceholder() {
		w("#\n")
		w("# BEFORE DEPLOYING: create the organizational unit, then replace every\n")
		w("# occurrence of %s below with the real OU id. AWS rejects the\n", ou)
		w("# template while the placeholder remains, so this cannot be forgotten silently.\n")
	}
	w("\n")
	w("Resources:\n")
	w("  AutomatVendorRole:\n")
	w("    Type: AWS::IAM::Role\n")
	w("    Properties:\n")
	w("      RoleName: %s\n", r.VendorRoleName)
	w("      Description: >-\n")
	w("        Lets account %s vend member accounts into OU %s. Managed by automat.\n", r.MemberAccountID, ou)
	w("      MaxSessionDuration: 3600\n")
	w("      AssumeRolePolicyDocument:\n")
	w("        Version: '2012-10-17'\n")
	w("        Statement:\n")
	w("          - Sid: AutomatMemberAccountMayAssumeWithExternalId\n")
	w("            Effect: Allow\n")
	w("            Principal:\n")
	w("              AWS: '%s'\n", r.trustPrincipal())
	w("            Action: sts:AssumeRole\n")
	w("            Condition:\n")
	w("              StringEquals:\n")
	// The confused-deputy defense. Without it, any account that learns the role
	// ARN could assume it; with it, only a caller told the ExternalId can.
	w("                sts:ExternalId: '%s'\n", r.ExternalID)
	w("      Policies:\n")
	w("        - PolicyName: automat-vend\n")
	w("          PolicyDocument:\n")
	w("            Version: '2012-10-17'\n")
	w("            Statement:\n")

	w("              # Account creation. The tag condition means every account this role\n")
	w("              # creates is attributable: an untagged account cannot be created at all.\n")
	w("              - Sid: CreateTaggedAccounts\n")
	w("                Effect: Allow\n")
	w("                Action:\n")
	w("                  - organizations:CreateAccount\n")
	w("                Resource: '*'\n")
	w("                Condition:\n")
	w("                  StringEquals:\n")
	w("                    aws:RequestTag/automat:vended-by: '%s'\n", r.MemberAccountID)
	w("                    aws:RequestTag/automat:ou: '%s'\n", ou)
	w("\n")
	w("              # Placement. This is the statement that bounds the blast radius, and it\n")
	w("              # is bounded at both ends because MoveAccount authorizes against the\n")
	w("              # destination parent AND the account being moved.\n")
	w("              #\n")
	w("              # Destination: this OU or one below it, by resource. Account: only one\n")
	w("              # this role vended, by condition. The account resource pattern cannot\n")
	w("              # express the second -- an Organizations account ARN encodes the\n")
	w("              # organization, not the account's OU, so account/<org>/* is every\n")
	w("              # account here. Without the condition this statement would read \"move\n")
	w("              # ANY account in the organization into this OU\", and since an account\n")
	w("              # has exactly one parent, moving one IN moves it OUT from under\n")
	w("              # whatever service control policies bound it before.\n")
	w("              - Sid: MoveAccountsIntoTheDelegatedSubtreeOnly\n")
	w("                Effect: Allow\n")
	w("                Action:\n")
	w("                  - organizations:MoveAccount\n")
	w("                Resource:\n")
	w("                  - !Sub 'arn:${AWS::Partition}:organizations::${AWS::AccountId}:account/%s/*'\n", r.OrgID)
	w("                  - !Sub 'arn:${AWS::Partition}:organizations::${AWS::AccountId}:ou/%s/%s'\n", r.OrgID, ou)
	w("                  - !Sub 'arn:${AWS::Partition}:organizations::${AWS::AccountId}:ou/%s/%s/*'\n", r.OrgID, ou)
	w("                Condition:\n")
	w("                  StringEquals:\n")
	w("                    aws:ResourceTag/automat:vended-by: '%s'\n", r.MemberAccountID)
	w("\n")
	w("              # Sub-OUs, restricted to the delegated subtree as the parent.\n")
	w("              - Sid: CreateOrganizationalUnitsInsideTheSubtreeOnly\n")
	w("                Effect: Allow\n")
	w("                Action:\n")
	w("                  - organizations:CreateOrganizationalUnit\n")
	w("                Resource:\n")
	w("                  - !Sub 'arn:${AWS::Partition}:organizations::${AWS::AccountId}:ou/%s/%s'\n", r.OrgID, ou)
	w("                  - !Sub 'arn:${AWS::Partition}:organizations::${AWS::AccountId}:ou/%s/%s/*'\n", r.OrgID, ou)
	w("\n")
	w("              # Tagging, restricted to automat's own tag namespace. Unrestricted,\n")
	w("              # this action would let the role write any tag onto any account or OU\n")
	w("              # in the organization -- including a tag central IT uses in a policy\n")
	w("              # condition of its own, which would make that condition forgeable.\n")
	w("              - Sid: TagOnlyInAutomatsNamespace\n")
	w("                Effect: Allow\n")
	w("                Action:\n")
	w("                  - organizations:TagResource\n")
	w("                Resource: '*'\n")
	w("                Condition:\n")
	w("                  ForAllValues:StringLike:\n")
	w("                    aws:TagKeys:\n")
	w("                      - 'automat:*'\n")
	w("\n")
	w("              # The reads that make the above verifiable. No policy actions appear\n")
	w("              # anywhere in this role -- those flow through the delegation policy in\n")
	w("              # delegation-policy.json, which is separately scoped and separately\n")
	w("              # reviewable.\n")
	w("              - Sid: ReadTheOrganization\n")
	w("                Effect: Allow\n")
	w("                Action:\n")
	for _, a := range vendorRoleActions {
		switch a.action {
		case "organizations:CreateAccount", "organizations:MoveAccount",
			"organizations:CreateOrganizationalUnit", "organizations:TagResource":
			continue // granted above, each with its own condition
		}
		w("                  - %s\n", a.action)
	}
	w("                Resource: '*'\n")
	w("      Tags:\n")
	w("        - Key: automat:managed-by\n")
	w("          Value: automat\n")
	w("        - Key: automat:vended-by\n")
	w("          Value: '%s'\n", r.MemberAccountID)
	w("        - Key: automat:ou\n")
	w("          Value: '%s'\n", ou)
	w("\n")
	w("Outputs:\n")
	w("  VendorRoleArn:\n")
	w("    Description: Set this as vendor_role_arn in the requesting account's automat config.\n")
	w("    Value: !GetAtt AutomatVendorRole.Arn\n")

	return []byte(b.String()), nil
}

// VendorRoleTF renders vendor-role.tf, the same role for a management account run
// by Terraform.
//
// It is the same grant, not an approximation of it: TestCFNAndTFGrantTheSameThing
// compares the action sets and the conditions, because two files that drift apart
// mean central IT approved one thing and deployed another.
func VendorRoleTF(r *Request) ([]byte, error) {
	if err := r.Validate(); err != nil {
		return nil, err
	}
	ou := r.ouScope()
	var b strings.Builder
	w := func(format string, args ...any) {
		if len(args) == 0 {
			b.WriteString(format)
			return
		}
		fmt.Fprintf(&b, format, args...)
	}

	w("# The automat vendor role, for a management account managed by Terraform.\n")
	w("#\n")
	w("# Equivalent to vendor-role.cfn.yaml in the same bundle -- deploy one, not both.\n")
	w("# Generated by automat %s at %s. Review before applying: this file is the\n", r.ToolVersion, r.GeneratedAt)
	w("# entire grant being requested, and it is meant to be read in full.\n")
	if r.ouIsPlaceholder() {
		w("#\n")
		w("# BEFORE APPLYING: create the organizational unit, then replace every\n")
		w("# occurrence of %s below with the real OU id.\n", ou)
	}
	w("\n")
	w("data \"aws_partition\" \"current\" {}\n")
	w("data \"aws_caller_identity\" \"management\" {}\n")
	w("\n")
	w("locals {\n")
	w("  automat_org_id      = \"%s\"\n", r.OrgID)
	w("  automat_target_ou   = \"%s\"\n", ou)
	w("  automat_member_acct = \"%s\"\n", r.MemberAccountID)
	w("  automat_org_arn_base = format(\n")
	// Terraform's own format verbs, not Go's. Written straight to the builder so
	// there is no chance of a printf pass reading them.
	b.WriteString("    \"arn:%s:organizations::%s\",\n")
	w("    data.aws_partition.current.partition,\n")
	w("    data.aws_caller_identity.management.account_id,\n")
	w("  )\n")
	w("}\n")
	w("\n")
	w("resource \"aws_iam_role\" \"automat_vendor\" {\n")
	w("  name                 = \"%s\"\n", r.VendorRoleName)
	w("  description          = \"Lets account %s vend member accounts into OU %s. Managed by automat.\"\n",
		r.MemberAccountID, ou)
	w("  max_session_duration = 3600\n")
	w("\n")
	w("  assume_role_policy = jsonencode({\n")
	w("    Version = \"2012-10-17\"\n")
	w("    Statement = [{\n")
	w("      Sid       = \"AutomatMemberAccountMayAssumeWithExternalId\"\n")
	w("      Effect    = \"Allow\"\n")
	w("      Principal = { AWS = \"%s\" }\n", r.trustPrincipal())
	w("      Action    = \"sts:AssumeRole\"\n")
	w("      # The confused-deputy defense: without this condition any account that\n")
	w("      # learns the role ARN could assume it.\n")
	w("      Condition = {\n")
	w("        StringEquals = { \"sts:ExternalId\" = \"%s\" }\n", r.ExternalID)
	w("      }\n")
	w("    }]\n")
	w("  })\n")
	w("\n")
	w("  tags = {\n")
	w("    \"automat:managed-by\" = \"automat\"\n")
	w("    \"automat:vended-by\"  = \"%s\"\n", r.MemberAccountID)
	w("    \"automat:ou\"         = \"%s\"\n", ou)
	w("  }\n")
	w("}\n")
	w("\n")
	w("resource \"aws_iam_role_policy\" \"automat_vend\" {\n")
	w("  name = \"automat-vend\"\n")
	w("  role = aws_iam_role.automat_vendor.id\n")
	w("\n")
	w("  policy = jsonencode({\n")
	w("    Version = \"2012-10-17\"\n")
	w("    Statement = [\n")
	w("      {\n")
	w("        # Every account this role creates is attributable: an untagged account\n")
	w("        # cannot be created at all.\n")
	w("        Sid      = \"CreateTaggedAccounts\"\n")
	w("        Effect   = \"Allow\"\n")
	w("        Action   = [\"organizations:CreateAccount\"]\n")
	w("        Resource = \"*\"\n")
	w("        Condition = {\n")
	w("          StringEquals = {\n")
	w("            \"aws:RequestTag/automat:vended-by\" = local.automat_member_acct\n")
	w("            \"aws:RequestTag/automat:ou\"        = local.automat_target_ou\n")
	w("          }\n")
	w("        }\n")
	w("      },\n")
	w("      {\n")
	w("        # The statement that bounds the blast radius, bounded at both ends:\n")
	w("        # MoveAccount authorizes against the destination parent AND the account\n")
	w("        # being moved. Destination by resource, account by condition -- an\n")
	w("        # Organizations account ARN encodes the organization, not the account's\n")
	w("        # OU, so the account pattern below is every account here. Without the\n")
	w("        # condition this would read \"move ANY account into this OU\", and since\n")
	w("        # an account has one parent, moving it IN moves it OUT from under\n")
	w("        # whatever service control policies bound it before.\n")
	w("        Sid    = \"MoveAccountsIntoTheDelegatedSubtreeOnly\"\n")
	w("        Effect = \"Allow\"\n")
	w("        Action = [\"organizations:MoveAccount\"]\n")
	w("        Resource = [\n")
	w("          \"${local.automat_org_arn_base}:account/${local.automat_org_id}/*\",\n")
	w("          \"${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}\",\n")
	w("          \"${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}/*\",\n")
	w("        ]\n")
	w("        Condition = {\n")
	w("          StringEquals = {\n")
	w("            \"aws:ResourceTag/automat:vended-by\" = local.automat_member_acct\n")
	w("          }\n")
	w("        }\n")
	w("      },\n")
	w("      {\n")
	w("        Sid      = \"CreateOrganizationalUnitsInsideTheSubtreeOnly\"\n")
	w("        Effect   = \"Allow\"\n")
	w("        Action   = [\"organizations:CreateOrganizationalUnit\"]\n")
	w("        Resource = [\n")
	w("          \"${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}\",\n")
	w("          \"${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}/*\",\n")
	w("        ]\n")
	w("      },\n")
	w("      {\n")
	w("        # Unrestricted, this would let the role write any tag onto any account\n")
	w("        # or OU in the organization -- including a tag central IT uses in a\n")
	w("        # policy condition of its own, which would make that condition forgeable.\n")
	w("        Sid      = \"TagOnlyInAutomatsNamespace\"\n")
	w("        Effect   = \"Allow\"\n")
	w("        Action   = [\"organizations:TagResource\"]\n")
	w("        Resource = \"*\"\n")
	w("        Condition = {\n")
	w("          \"ForAllValues:StringLike\" = {\n")
	w("            \"aws:TagKeys\" = [\"automat:*\"]\n")
	w("          }\n")
	w("        }\n")
	w("      },\n")
	w("      {\n")
	w("        # No policy actions appear anywhere in this role -- those flow through\n")
	w("        # the delegation policy in delegation-policy.json, which is separately\n")
	w("        # scoped and separately reviewable.\n")
	w("        Sid      = \"ReadTheOrganization\"\n")
	w("        Effect   = \"Allow\"\n")
	w("        Resource = \"*\"\n")
	w("        Action = [\n")
	for _, a := range vendorRoleActions {
		switch a.action {
		case "organizations:CreateAccount", "organizations:MoveAccount",
			"organizations:CreateOrganizationalUnit", "organizations:TagResource":
			continue
		}
		w("          \"%s\",\n", a.action)
	}
	w("        ]\n")
	w("      },\n")
	w("    ]\n")
	w("  })\n")
	w("}\n")
	w("\n")
	w("output \"automat_vendor_role_arn\" {\n")
	w("  description = \"Set this as vendor_role_arn in the requesting account's automat config.\"\n")
	w("  value       = aws_iam_role.automat_vendor.arn\n")
	w("}\n")

	return []byte(b.String()), nil
}
