# The automat vendor role, for a management account managed by Terraform.
#
# Equivalent to vendor-role.cfn.yaml in the same bundle -- deploy one, not both.
# Generated by automat v0.1.0-test at 2026-08-05T14:00:00Z. Review before applying: this file is the
# entire grant being requested, and it is meant to be read in full.

data "aws_partition" "current" {}
data "aws_caller_identity" "management" {}

locals {
  automat_org_id      = "o-exampleorgid"
  automat_target_ou   = "ou-exam-research1"
  automat_member_acct = "222222222222"
  automat_org_arn_base = format(
    "arn:%s:organizations::%s",
    data.aws_partition.current.partition,
    data.aws_caller_identity.management.account_id,
  )
}

resource "aws_iam_role" "automat_vendor" {
  name                 = "automat-vendor"
  description          = "Lets account 222222222222 vend member accounts into OU ou-exam-research1. Managed by automat."
  max_session_duration = 3600

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "AutomatMemberAccountMayAssumeWithExternalId"
      Effect    = "Allow"
      Principal = { AWS = "arn:aws:iam::222222222222:role/automat-runner" }
      Action    = "sts:AssumeRole"
      # The confused-deputy defense: without this condition any account that
      # learns the role ARN could assume it.
      Condition = {
        StringEquals = { "sts:ExternalId" = "EXAMPLE-NOT-A-REAL-EXTERNAL-ID" }
      }
    }]
  })

  tags = {
    "automat:managed-by" = "automat"
    "automat:vended-by"  = "222222222222"
    "automat:ou"         = "ou-exam-research1"
  }
}

resource "aws_iam_role_policy" "automat_vend" {
  name = "automat-vend"
  role = aws_iam_role.automat_vendor.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        # Every account this role creates is attributable: an untagged account
        # cannot be created at all.
        Sid      = "CreateTaggedAccounts"
        Effect   = "Allow"
        Action   = ["organizations:CreateAccount"]
        Resource = "*"
        Condition = {
          StringEquals = {
            "aws:RequestTag/automat:vended-by" = local.automat_member_acct
            "aws:RequestTag/automat:ou"        = local.automat_target_ou
          }
        }
      },
      {
        # The statement that bounds the blast radius, bounded at both ends:
        # MoveAccount authorizes against the destination parent AND the account
        # being moved. Destination by resource, account by condition -- an
        # Organizations account ARN encodes the organization, not the account's
        # OU, so the account pattern below is every account here. Without the
        # condition this would read "move ANY account into this OU", and since
        # an account has one parent, moving it IN moves it OUT from under
        # whatever service control policies bound it before.
        Sid    = "MoveAccountsIntoTheDelegatedSubtreeOnly"
        Effect = "Allow"
        Action = ["organizations:MoveAccount"]
        Resource = [
          "${local.automat_org_arn_base}:account/${local.automat_org_id}/*",
          "${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}",
          "${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}/*",
        ]
        Condition = {
          StringEquals = {
            "aws:ResourceTag/automat:vended-by" = local.automat_member_acct
          }
        }
      },
      {
        Sid      = "CreateOrganizationalUnitsInsideTheSubtreeOnly"
        Effect   = "Allow"
        Action   = ["organizations:CreateOrganizationalUnit"]
        Resource = [
          "${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}",
          "${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}/*",
        ]
      },
      {
        # Unrestricted, this would let the role write any tag onto any account
        # or OU in the organization -- including a tag central IT uses in a
        # policy condition of its own, which would make that condition forgeable.
        Sid      = "TagOnlyInAutomatsNamespace"
        Effect   = "Allow"
        Action   = ["organizations:TagResource"]
        Resource = "*"
        Condition = {
          "ForAllValues:StringLike" = {
            "aws:TagKeys" = ["automat:*"]
          }
        }
      },
      {
        # No policy actions appear anywhere in this role -- those flow through
        # the delegation policy in delegation-policy.json, which is separately
        # scoped and separately reviewable.
        Sid      = "ReadTheOrganization"
        Effect   = "Allow"
        Resource = "*"
        Action = [
          "organizations:DescribeCreateAccountStatus",
          "organizations:DescribeAccount",
          "organizations:DescribeOrganizationalUnit",
          "organizations:ListParents",
          "organizations:ListAccountsForParent",
          "organizations:ListOrganizationalUnitsForParent",
          "organizations:ListRoots",
        ]
      },
    ]
  })
}

output "automat_vendor_role_arn" {
  description = "Set this as vendor_role_arn in the requesting account's automat config."
  value       = aws_iam_role.automat_vendor.arn
}
