# The automat vendor role, for a management account managed by Terraform.
#
# Equivalent to vendor-role.cfn.yaml in the same bundle -- deploy one, not both.
# Generated by automat v0.1.0-test at 2026-08-05T14:00:00Z. Review before applying: this file is the
# entire grant being requested, and it is meant to be read in full.
#
# BEFORE APPLYING: create the organizational unit, then replace every
# occurrence of ou-REPLACE-WITH-THE-NEW-OU-ID below with the real OU id.

variable "automat_external_id" {
  type      = string
  sensitive = true
  nullable  = false
  description = <<-EOT
    The shared secret this role will require in sts:AssumeRole. Generate it
    yourself -- do not let anyone send you one -- and give it to the requester over
    a channel you would use for a password. Suggested: openssl rand -hex 24.

    sensitive = true keeps this out of plan output; it does not keep it out of
    Terraform state, which will contain the trust policy. Treat the state file
    accordingly -- that is true of it already.

    It is not a password: it stops a third party who learns this role's ARN from
    assuming it, and it does not defend against compromised credentials in
    account 222222222222.
  EOT

  validation {
    condition     = can(regex("^[A-Za-z0-9+=,.@:/_-]+$", var.automat_external_id))
    error_message = "Must use only the characters AWS accepts in an ExternalId."
  }
  validation {
    condition = (
      length(var.automat_external_id) >= 16 && length(var.automat_external_id) <= 1224
    )
    error_message = "Must be 16-1224 characters. Shorter is guessable."
  }
}

data "aws_partition" "current" {}
data "aws_caller_identity" "management" {}

locals {
  automat_org_id      = "o-exampleorgid"
  automat_target_ou   = "ou-REPLACE-WITH-THE-NEW-OU-ID"
  automat_member_acct = "222222222222"
  automat_org_arn_base = format(
    "arn:%s:organizations::%s",
    data.aws_partition.current.partition,
    data.aws_caller_identity.management.account_id,
  )
}

resource "aws_iam_role" "automat_vendor" {
  name                 = "automat-vendor-research"
  description          = "Lets account 222222222222 vend member accounts into OU ou-REPLACE-WITH-THE-NEW-OU-ID. Managed by automat."
  max_session_duration = 3600

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "AutomatMemberAccountMayAssumeWithExternalId"
      Effect    = "Allow"
      Principal = { AWS = "arn:aws:iam::222222222222:root" }
      Action    = "sts:AssumeRole"
      # The confused-deputy defense: without this condition any account that
      # learns the role ARN could assume it. A var reference rather than a
      # literal -- the value is chosen by whoever applies this and is never
      # carried in the bundle.
      Condition = {
        StringEquals = { "sts:ExternalId" = var.automat_external_id }
      }
    }]
  })

  tags = {
    "automat:managed-by" = "automat"
    "automat:vended-by"  = "222222222222"
    "automat:ou"         = "ou-REPLACE-WITH-THE-NEW-OU-ID"
  }
}

resource "aws_iam_role_policy" "automat_vend" {
  name = "automat-vend"
  role = aws_iam_role.automat_vendor.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        # Every account this role creates is attributable: an untagged account
        # cannot be created at all.
        Sid      = "CreateTaggedAccounts"
        Effect   = "Allow"
        Action   = ["organizations:CreateAccount"]
        Resource = "*"
        Condition = {
          StringEquals = {
            "aws:RequestTag/automat:vended-by" = local.automat_member_acct
            "aws:RequestTag/automat:ou"        = local.automat_target_ou
          }
        }
      },
      {
        # The statement that bounds the blast radius, bounded at both ends:
        # MoveAccount authorizes against the destination parent AND the account
        # being moved. Destination by resource, account by condition -- an
        # Organizations account ARN encodes the organization, not the account's
        # OU, so the account pattern below is every account here. Without the
        # condition this would read "move ANY account into this OU", and since
        # an account has one parent, moving it IN moves it OUT from under
        # whatever service control policies bound it before.
        Sid    = "MoveAccountsIntoTheDelegatedSubtreeOnly"
        Effect = "Allow"
        Action = ["organizations:MoveAccount"]
        Resource = [
          "${local.automat_org_arn_base}:account/${local.automat_org_id}/*",
          "${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}",
          "${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}/*",
        ]
        Condition = {
          StringEquals = {
            "aws:ResourceTag/automat:vended-by" = local.automat_member_acct
          }
        }
      },
      {
        Sid      = "CreateOrganizationalUnitsInsideTheSubtreeOnly"
        Effect   = "Allow"
        Action   = ["organizations:CreateOrganizationalUnit"]
        Resource = [
          "${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}",
          "${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}/*",
        ]
      },
      {
        # Two bounds, both load-bearing.
        #
        # The RESOURCE bound excludes policies: on "*" this statement would
        # reach every service control policy in the organization, and tagging
        # one of yours with automat:managed-by=automat would hand the delegation
        # policy permission to rewrite it -- that document gates update, delete,
        # and detach on exactly that tag.
        #
        # The KEY bound is an explicit list rather than automat:*, because
        # automat:vended-by and automat:ou are read by conditions elsewhere in
        # this bundle. Both are applied once at CreateAccount via aws:RequestTag,
        # so nothing legitimate re-sets them; the keys below are inventory labels
        # that no condition reads.
        # Accounts and OUs are split because only one can be confined by a tag:
        # account/<org>/* is every account in the organization, so that statement
        # carries a vended-by condition, while a fresh OU has no tags at all and
        # its ARN does encode the subtree.
        Sid      = "TagAccountsThisRoleVended"
        Effect   = "Allow"
        Action   = ["organizations:TagResource"]
        Resource = ["${local.automat_org_arn_base}:account/${local.automat_org_id}/*"]
        Condition = {
          StringEquals = {
            "aws:ResourceTag/automat:vended-by" = local.automat_member_acct
          }
          "ForAllValues:StringEquals" = {
            "aws:TagKeys" = ["automat:artifact-id", "automat:artifact-sha256", "automat:version"]
          }
        }
      },
      {
        Sid      = "TagOrganizationalUnitsInTheSubtree"
        Effect   = "Allow"
        Action   = ["organizations:TagResource"]
        Resource = [
          "${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}",
          "${local.automat_org_arn_base}:ou/${local.automat_org_id}/${local.automat_target_ou}/*",
        ]
        Condition = {
          "ForAllValues:StringEquals" = {
            "aws:TagKeys" = ["automat:artifact-id", "automat:artifact-sha256", "automat:version"]
          }
        }
      },
      {
        # No policy actions appear anywhere in this role -- those flow through
        # the delegation policy in delegation-policy.json, which is separately
        # scoped and separately reviewable.
        Sid      = "ReadTheOrganization"
        Effect   = "Allow"
        Resource = "*"
        Action = [
          "organizations:DescribeCreateAccountStatus",
          "organizations:DescribeAccount",
          "organizations:DescribeOrganizationalUnit",
          "organizations:ListParents",
          "organizations:ListAccountsForParent",
          "organizations:ListOrganizationalUnitsForParent",
          "organizations:ListRoots",
        ]
      },
    ]
  })
}

output "automat_vendor_role_arn" {
  description = "Set this as vendor_role_arn in the requesting account's automat config."
  value       = aws_iam_role.automat_vendor.arn
}
